### ISSUE TITLE
Vendoring

### ISSUE THREAD

**Issue by looneym** [knpwrs/dotfiles#1]
Hello there,

I've been considering vendoring a bunch of packages into my dotfiles repo and using it to generate a tarball which can be easily "mounted" on a remote system by modifying the PATH in a similar way to what you're doing here. 

Your setup looks really good, are you still using this vendored approach regularly? Any gotchas? Cheers

**Comment by knpwrs** [comment]
I'm not quite sure I understand the question. I have third-party dependencies committed directly to the repo so I don't have to deal with strange package managers or submodules.
